app:
  version: ${project.version}
  name: ${project.name}

server:
  port: 11000

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-api-svc
  cloud:
    gateway:
      default-filters:
#        - TokenRelay - keyclock 테스트용
        - name: AuthorizationFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: false
            postLogger: true
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://100.100.103.163:31985/realms/bcloud
#            authorization-uri: http://100.100.103.163:31985/realms/bcloud/protocol/openid-connect/auth
#            userinfo-uri: http://100.100.103.163:31985/realms/bcloud/protocol/openid-connect/userinfo
#            user-name-attribute: preferred_username
#        registration:
#          keycloak:
#            client-id: apigw
#            client-secret: obPG9DY7Tm1wMS6er4xSiYjDLm3GufxL